catatanku/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.http import HttpResponse

from . import views

urlpatterns = [
	url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
	url(r'^dashboard/', include('dashboard.urls')),
]

dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'
urlpatterns = [
	url(r'^$', views.list_view, name="list"),
	url(r'^insert/$', views.insert_view, name="insert"),
	url(r'^update/(?P<update_id>[0-9]+)$', views.update_view, name="update"),
	url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete_view, name="delete"),
]

dashboard/models.py
from django.db import models

class Note(models.Model):
	judul = models.CharField(max_length = 100)
	isi = models.TextField()
	def __str__(self):
		return "{}".format(self.id)

dashboard/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
	class Meta:
		model = Note
		fields = ['judul', 'isi']

catatanku/views.py
from django.shortcuts import render

def index(req):
	context = {
		'deskripsi': 'selamat datang Resia! semoga hari-harimu menyenangkan 💖'
	}
	return render(req, 'index.html', context)

dashboard/views.py
from django.shortcuts import render, redirect
from .models import Note
from .forms import NoteForm

def list_view(req):
	note = Note.objects.all()
	context = {
		'note': note
	}
	return render(req, 'list.html', context)

def insert_view(req):
	noteForm = NoteForm(req.POST or None)
	if req.method == 'POST':
		if noteForm.is_valid():
			noteForm.save()
		return redirect("dashboard:list")
	context = {
		'noteForm' : noteForm,
		'tipe': 'Insert',
	}
	return render(req, 'insert.html', context)

def delete_view(req, delete_id):
	Note.objects.filter(id = delete_id).delete()
	return redirect("dashboard:list")

def update_view(req, update_id):
	noteForm_lama = Note.objects.get(id = update_id)
	data = {
		'judul': noteForm_lama.judul,
		'isi': noteForm_lama.isi,
	}
	noteForm = NoteForm(req.POST or None, initial = data, instance = noteForm_lama)
	if req.method == 'POST':
		if noteForm.is_valid():
			noteForm.save()
		return redirect("dashboard:list")
	context = {
		'noteForm': noteForm,
		'tipe': 'Update',
	}
	return render(req, 'insert.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Catatanku</title>
		<link rel="stylesheet" href="/static/style.css" />
	</head>

	<body>
		<div class="wrapper">
			<header>
				<h1>Note App</h1>
			</header>
			<nav>
				<p>
					<a href="{% url 'dashboard:list' %}" class="button"
						>Menuju ke aplikasi</a
					>
				</p>
			</nav>
			<main>
				<p>{{ deskripsi }}</p>
			</main>
		</div>
	</body>
</html>

templates/insert.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Catatanku</title>
	</head>
	<body>
		<h1>Note Insert / Update</h1>
		<form method="POST">
			{% csrf_token %}
			<table>
				{{ noteForm.as_table }}
			</table>
			<button type="submit">KIRIM</button>
		</form>
	</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Catatanku</title>
	<link rel="stylesheet" href="/static/style.css" />
</head>

<body>
	<div class="wrapper">
		<header>
			<h1>Note List</h1>
		</header>
		<nav>
			<p><a href="{% url 'dashboard:insert' %}">Add Note 📓</a></p>
		</nav>
		<section>
			{% for item in note %}
			<div class="note">
				<h3>{{ item.judul }}</h3>
				<p>{{ item.isi }}</p>
				<div class="control">
					<a href="{% url 'dashboard:update' item.id %}">update ✍</a>
					<a href="{% url 'dashboard:delete' item.id %}">delete ❌</a>
				</div>
			</div>
			{% endfor %}
		</section>
	</div>
</body>

</html>